apiVersion: mesh.mesh.iglin.io/v1alpha1
kind: ScopedRouteConfiguration
metadata:
  labels:
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/managed-by: kustomize
  name: scopedrouteconfiguration-sample
spec:
  # TODO(user): Add fields here
