apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "control-plane.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
